# MySQL Connection
pring.datasource.url=jdbc:mysql://localhost:3306/hmtravelling_agency?createDatabaseIfNotExist=true

# 2. Your MySQL Login Credentials
spring.datasource.username=root
spring.datasource.password=haxiq889
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings (Auto-creates your tables based on Java classes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect